server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10
#微信的配置
weixin:
  config:



#日志配置，固定写法
logging:
  level:
    root: info
  config: classpath:logback-spring.xml