server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10
#微信的配置
weixin:
  config:
    #微信用户id，公众号持有的用户
    originalid: gh_31451429fa36
    #共同约定receive方法的token
    token: b8b0
    app-id: wx17c5129804c2590c
    app-secret: 6d244f0143aaf93fb72289d71cca5656
    template-id: AIBKbI1bf3LnfM8Yov00Y8UxwBxlcmmapVRuVE62nmw
    touser: oPwuY6ucrrwDGnYkD151fIvJV6hc

#日志配置，固定写法
logging:
  level:
    root: info
  config: classpath:logback-spring.xml